### ISSUE TITLE
Lazily load images from community reports

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#112] opened 2015-08-10 22:55 UTC
When the page initially loads, we are loading all of the images for all of our community reports. If we have lots of reports with images, this greatly affects performance. The images are stored in an AWS S3 bucket using the boto package. It would be nice to enable the ability to lazily load a place's image only when the place is selected.

For list view, we can limit the view to only ~10 places, or work with only the thumbnails. As the user scrolls, we can proceed to fetch those images.

See use case example for the 2800+ place records that are loading with slow performance at http://map.12000raingardens.org

This issue corresponds with this issue on our API: https://github.com/smartercleanup/api/issues/8

**Comment by LukeSwart** [comment] 2016-06-09 02:47
As a quick first step, I think if we can prevent the attachments from loading by commenting out these lines here: https://github.com/smartercleanup/platform/blob/develop/src/sa_web/static/js/models.js#L161-L168

After that, we can work on loading the attachments only when the place is clicked (or when we enter the place list-view).

**Comment by zmbc** [comment] 2016-10-21 04:07
Closing as a dupe of #451. Moving these comments over because they are useful/relevant.

**Closed by zmbc** 2016-10-21 04:07 UTC
