### ISSUE TITLE
Fix place list view filtering

### ISSUE THREAD

**Issue by goldpbear** [smartercleanup/platform#414] opened 2016-08-25 20:41 UTC
There is a lingering bug from the multidataset refactor that renders the `applyFilters()` method useless. It seems to affect some flavors but not others.

**Comment by LukeSwart** [comment] 2016-08-26 05:15
This seems to be a duplicate of #383, no? 

Either way, I tested your PR #418 and it looks fixed!

**Comment by goldpbear** [comment] 2016-08-26 06:48
Yes, most definitely a duplicate! Sorry, should have checked the issue list first

**Closed** 2016-08-26 17:46 UTC
